"""
You are given three positive integers num1, num2, and num3.

The key of num1, num2, and num3 is defined as a four-digit number such that:

    Initially, if any number has less than four digits, it is padded with leading zeros.
    The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.

Return the key of the three numbers without leading zeros (if any).
"""


class Solution:
    def update(self, num, index, m):
        if len(num) >= -index:
            return min(m, int(num[index]))
        else:
            return 0


    def generateKey(self, num1: int, num2: int, num3: int) -> int:
        key = []
        num1, num2, num3 = str(num1), str(num2), str(num3)
        
        for i in range(-1, -5, -1):
            m = float("inf")
            m = self.update(str(num1), i, m)
            m = self.update(str(num2), i, m)
            m = self.update(str(num3), i, m)
            key = [str(m)] + key if key else [str(m)]
        
        return int("".join(key))
                
